#!/bin/bash
#SBATCH --job-name=fourway_rerun
#SBATCH --output=incremental_experiments/results/slurm_fourway_%A_task%a.log
#SBATCH --time=04:00:00
#SBATCH --mem=64G
#SBATCH --cpus-per-task=4
#SBATCH --partition=general
#SBATCH --array=0-47
#SBATCH --requeue
#SBATCH --open-mode=append

# Regenerate the four-way action logs (DP vs MYOPIC vs GNN-Q vs MLP-Q, root
# action + full trajectory) for EVERY rung, both gene counts, 3 seeds.
#
# Why: the fourway JSONs currently on disk are dated 2026-07-25 to 08-10. They
# therefore predate BOTH
#   (a) the 3-gene allele-frequency correction (08-15/16), and
#   (b) the E0-E9 retrain on that corrected data (jobs 2199861-2199871,
#       finished 08-22 21:20-22:08).
# Every 3-gene root-agreement / whole-trajectory number derived from them is
# computed against superseded data AND superseded checkpoints. The per-rung
# ratio2 numbers were regenerated by the retrain and are fine; these are not.
#
# 48 tasks = 8 rungs x {3-gene, 2-gene} x 3 seeds.
# Deliberately NO skip guard: overwriting the stale outputs is the entire point.

cd /net/projects/ranalab/rajhansini/replication_16features

RUNGS=(e0 e1 e2 e4 e5 e6 e7 e9)

RUNG_IDX=$(( SLURM_ARRAY_TASK_ID / 6 ))
REM=$(( SLURM_ARRAY_TASK_ID % 6 ))
if [ "$REM" -lt 3 ]; then GENES=3; SEED=$REM; else GENES=2; SEED=$(( REM - 3 )); fi
RUNG=${RUNGS[$RUNG_IDX]}

echo "task=$SLURM_ARRAY_TASK_ID -> rung=$RUNG genes=$GENES seed=$SEED"

/net/projects/ranalab/rajhansini/conda_envs/genetic-rl/bin/python \
  incremental_experiments/log_${RUNG}_fourway.py --genes "$GENES" --seed "$SEED" --device cpu
